export type Permission =
  | 'AUTH.LOGIN'
  | 'AUTH.LOGOUT'
  | 'AUTH.REFRESH_TOKEN'
  | 'USER.VIEW'
  | 'USER.CREATE'
  | 'USER.UPDATE'
  | 'USER.DELETE'
  | 'USER.RESTORE'
  | 'ROLE.VIEW'
  | 'ROLE.CREATE'
  | 'ROLE.UPDATE'
  | 'ROLE.DELETE'
  | 'CUSTOMER.VIEW'
  | 'CUSTOMER.CREATE'
  | 'CUSTOMER.UPDATE'
  | 'CUSTOMER.DELETE'
  | 'CUSTOMER.RESTORE'
  | 'CUSTOMER.EXPORT'
  | 'PRODUCT.VIEW'
  | 'PRODUCT.CREATE'
  | 'PRODUCT.UPDATE'
  | 'PRODUCT.DELETE'
  | 'PRODUCT.RESTORE'
  | 'PRODUCT.IMPORT'
  | 'PRODUCT.EXPORT'
  | 'PRODUCT.UPLOAD_IMAGE'
  | 'CATEGORY.VIEW'
  | 'CATEGORY.CREATE'
  | 'CATEGORY.UPDATE'
  | 'CATEGORY.DELETE'
  | 'WAREHOUSE.VIEW'
  | 'WAREHOUSE.CREATE'
  | 'WAREHOUSE.UPDATE'
  | 'WAREHOUSE.DELETE'
  | 'INVENTORY.VIEW'
  | 'INVENTORY.STOCK_IN'
  | 'INVENTORY.STOCK_OUT'
  | 'INVENTORY.MOVEMENT.VIEW'
  | 'INVENTORY.ALERTS.VIEW'
  | 'INVENTORY.ANALYTICS'
  | 'SALES.VIEW'
  | 'SALES.CREATE'
  | 'SALES.UPDATE'
  | 'SALES.DELETE'
  | 'SALES.CONFIRM'
  | 'SALES.CANCEL'
  | 'INVOICE.VIEW'
  | 'INVOICE.CREATE'
  | 'INVOICE.DOWNLOAD'
  | 'INVOICE.EMAIL'
  | 'INVOICE.PAYMENT.UPDATE'
  | 'RETURN.VIEW'
  | 'RETURN.CREATE'
  | 'RETURN.APPROVE'
  | 'RETURN.REJECT'
  | 'DASHBOARD.VIEW'
  | 'REPORT.SALES'
  | 'REPORT.INVENTORY'
  | 'REPORT.CUSTOMERS'
  | 'EMAIL.SEND'
  | 'EMAIL.HISTORY'
  | 'AUDIT.VIEW'
  | 'AUDIT.EXPORT';

export type UserRole = 'ADMIN' | 'SALES' | 'WAREHOUSE' | 'ACCOUNTS';

/**
 * Permission-Role Matrix
 * Maps each permission to the roles that are allowed to perform it.
 */
export const PERMISSIONS: Record<Permission, UserRole[]> = {
  // Auth
  'AUTH.LOGIN': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],
  'AUTH.LOGOUT': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],
  'AUTH.REFRESH_TOKEN': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],

  // User Management (Admin only except view)
  'USER.VIEW': ['ADMIN'],
  'USER.CREATE': ['ADMIN'],
  'USER.UPDATE': ['ADMIN'],
  'USER.DELETE': ['ADMIN'],
  'USER.RESTORE': ['ADMIN'],

  // Role Management
  'ROLE.VIEW': ['ADMIN'],
  'ROLE.CREATE': ['ADMIN'],
  'ROLE.UPDATE': ['ADMIN'],
  'ROLE.DELETE': ['ADMIN'],

  // Customer
  'CUSTOMER.VIEW': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],
  'CUSTOMER.CREATE': ['ADMIN', 'SALES'],
  'CUSTOMER.UPDATE': ['ADMIN', 'SALES'],
  'CUSTOMER.DELETE': ['ADMIN'],
  'CUSTOMER.RESTORE': ['ADMIN'],
  'CUSTOMER.EXPORT': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],

  // Product
  'PRODUCT.VIEW': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],
  'PRODUCT.CREATE': ['ADMIN'],
  'PRODUCT.UPDATE': ['ADMIN', 'WAREHOUSE'],
  'PRODUCT.DELETE': ['ADMIN'],
  'PRODUCT.RESTORE': ['ADMIN'],
  'PRODUCT.IMPORT': ['ADMIN'],
  'PRODUCT.EXPORT': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],
  'PRODUCT.UPLOAD_IMAGE': ['ADMIN', 'WAREHOUSE'],

  // Category
  'CATEGORY.VIEW': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],
  'CATEGORY.CREATE': ['ADMIN'],
  'CATEGORY.UPDATE': ['ADMIN'],
  'CATEGORY.DELETE': ['ADMIN'],

  // Warehouse
  'WAREHOUSE.VIEW': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],
  'WAREHOUSE.CREATE': ['ADMIN'],
  'WAREHOUSE.UPDATE': ['ADMIN'],
  'WAREHOUSE.DELETE': ['ADMIN'],

  // Inventory
  'INVENTORY.VIEW': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],
  'INVENTORY.STOCK_IN': ['ADMIN', 'WAREHOUSE'],
  'INVENTORY.STOCK_OUT': ['ADMIN', 'WAREHOUSE'],
  'INVENTORY.MOVEMENT.VIEW': ['ADMIN', 'WAREHOUSE'],
  'INVENTORY.ALERTS.VIEW': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],
  'INVENTORY.ANALYTICS': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],

  // Sales Orders
  'SALES.VIEW': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],
  'SALES.CREATE': ['ADMIN', 'SALES', 'WAREHOUSE'],
  'SALES.UPDATE': ['ADMIN', 'SALES', 'WAREHOUSE'],
  'SALES.DELETE': ['ADMIN'],
  'SALES.CONFIRM': ['ADMIN', 'SALES', 'WAREHOUSE'],
  'SALES.CANCEL': ['ADMIN', 'SALES', 'WAREHOUSE'],

  // Invoice
  'INVOICE.VIEW': ['ADMIN', 'SALES', 'ACCOUNTS'],
  'INVOICE.CREATE': ['ADMIN', 'ACCOUNTS'],
  'INVOICE.DOWNLOAD': ['ADMIN', 'SALES', 'ACCOUNTS'],
  'INVOICE.EMAIL': ['ADMIN', 'SALES', 'ACCOUNTS'],
  'INVOICE.PAYMENT.UPDATE': ['ADMIN', 'ACCOUNTS'],

  // Returns
  'RETURN.VIEW': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],
  'RETURN.CREATE': ['ADMIN', 'SALES', 'WAREHOUSE'],
  'RETURN.APPROVE': ['ADMIN', 'WAREHOUSE'],
  'RETURN.REJECT': ['ADMIN', 'WAREHOUSE'],

  // Dashboard & Reports
  'DASHBOARD.VIEW': ['ADMIN', 'SALES', 'WAREHOUSE', 'ACCOUNTS'],
  'REPORT.SALES': ['ADMIN', 'SALES', 'ACCOUNTS'],
  'REPORT.INVENTORY': ['ADMIN', 'WAREHOUSE', 'ACCOUNTS'],
  'REPORT.CUSTOMERS': ['ADMIN', 'SALES', 'ACCOUNTS'],

  // Email / Notifications
  'EMAIL.SEND': ['ADMIN', 'SALES', 'ACCOUNTS'],
  'EMAIL.HISTORY': ['ADMIN', 'ACCOUNTS'],

  // Audit Logs
  'AUDIT.VIEW': ['ADMIN'],
  'AUDIT.EXPORT': ['ADMIN'],
};
