/**
 * Permission constants matching backend permissions.ts
 */
export const PERMISSIONS = {
  // Auth
  AUTH_LOGIN: 'AUTH.LOGIN',
  AUTH_LOGOUT: 'AUTH.LOGOUT',
  AUTH_REFRESH_TOKEN: 'AUTH.REFRESH_TOKEN',

  // User Management
  USER_VIEW: 'USER.VIEW',
  USER_CREATE: 'USER.CREATE',
  USER_UPDATE: 'USER.UPDATE',
  USER_DELETE: 'USER.DELETE',
  USER_RESTORE: 'USER.RESTORE',

  // Role Management
  ROLE_VIEW: 'ROLE.VIEW',
  ROLE_CREATE: 'ROLE.CREATE',
  ROLE_UPDATE: 'ROLE.UPDATE',
  ROLE_DELETE: 'ROLE.DELETE',

  // Customer
  CUSTOMER_VIEW: 'CUSTOMER.VIEW',
  CUSTOMER_CREATE: 'CUSTOMER.CREATE',
  CUSTOMER_UPDATE: 'CUSTOMER.UPDATE',
  CUSTOMER_DELETE: 'CUSTOMER.DELETE',
  CUSTOMER_RESTORE: 'CUSTOMER.RESTORE',
  CUSTOMER_EXPORT: 'CUSTOMER.EXPORT',

  // Product
  PRODUCT_VIEW: 'PRODUCT.VIEW',
  PRODUCT_CREATE: 'PRODUCT.CREATE',
  PRODUCT_UPDATE: 'PRODUCT.UPDATE',
  PRODUCT_DELETE: 'PRODUCT.DELETE',
  PRODUCT_RESTORE: 'PRODUCT.RESTORE',
  PRODUCT_IMPORT: 'PRODUCT.IMPORT',
  PRODUCT_EXPORT: 'PRODUCT.EXPORT',
  PRODUCT_UPLOAD_IMAGE: 'PRODUCT.UPLOAD_IMAGE',

  // Category
  CATEGORY_VIEW: 'CATEGORY.VIEW',
  CATEGORY_CREATE: 'CATEGORY.CREATE',
  CATEGORY_UPDATE: 'CATEGORY.UPDATE',
  CATEGORY_DELETE: 'CATEGORY.DELETE',

  // Warehouse
  WAREHOUSE_VIEW: 'WAREHOUSE.VIEW',
  WAREHOUSE_CREATE: 'WAREHOUSE.CREATE',
  WAREHOUSE_UPDATE: 'WAREHOUSE.UPDATE',
  WAREHOUSE_DELETE: 'WAREHOUSE.DELETE',

  // Inventory
  INVENTORY_VIEW: 'INVENTORY.VIEW',
  INVENTORY_STOCK_IN: 'INVENTORY.STOCK_IN',
  INVENTORY_STOCK_OUT: 'INVENTORY.STOCK_OUT',
  INVENTORY_MOVEMENT_VIEW: 'INVENTORY.MOVEMENT.VIEW',
  INVENTORY_ALERTS_VIEW: 'INVENTORY.ALERTS.VIEW',
  INVENTORY_ANALYTICS: 'INVENTORY.ANALYTICS',

  // Sales Orders
  SALES_VIEW: 'SALES.VIEW',
  SALES_CREATE: 'SALES.CREATE',
  SALES_UPDATE: 'SALES.UPDATE',
  SALES_DELETE: 'SALES.DELETE',
  SALES_CONFIRM: 'SALES.CONFIRM',
  SALES_CANCEL: 'SALES.CANCEL',

  // Invoice
  INVOICE_VIEW: 'INVOICE.VIEW',
  INVOICE_CREATE: 'INVOICE.CREATE',
  INVOICE_DOWNLOAD: 'INVOICE.DOWNLOAD',
  INVOICE_EMAIL: 'INVOICE.EMAIL',
  INVOICE_PAYMENT_UPDATE: 'INVOICE.PAYMENT.UPDATE',

  // Returns
  RETURN_VIEW: 'RETURN.VIEW',
  RETURN_CREATE: 'RETURN.CREATE',
  RETURN_APPROVE: 'RETURN.APPROVE',
  RETURN_REJECT: 'RETURN.REJECT',

  // Dashboard & Reports
  DASHBOARD_VIEW: 'DASHBOARD.VIEW',
  REPORT_SALES: 'REPORT.SALES',
  REPORT_INVENTORY: 'REPORT.INVENTORY',
  REPORT_CUSTOMERS: 'REPORT.CUSTOMERS',

  // Email / Notifications
  EMAIL_SEND: 'EMAIL.SEND',
  EMAIL_HISTORY: 'EMAIL.HISTORY',

  // Audit Logs
  AUDIT_VIEW: 'AUDIT.VIEW',
  AUDIT_EXPORT: 'AUDIT.EXPORT',
};

/**
 * Permission-to-Role mapping (mirrors backend PERMISSIONS)
 */
const ROLE_PERMISSIONS = {
  ADMIN: Object.values(PERMISSIONS),
  SALES: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.AUTH_REFRESH_TOKEN,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_EXPORT,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_EXPORT,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ALERTS_VIEW,
    PERMISSIONS.INVENTORY_ANALYTICS,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_UPDATE,
    PERMISSIONS.SALES_CONFIRM,
    PERMISSIONS.SALES_CANCEL,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_DOWNLOAD,
    PERMISSIONS.INVOICE_EMAIL,
    PERMISSIONS.RETURN_VIEW,
    PERMISSIONS.RETURN_CREATE,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORT_SALES,
    PERMISSIONS.REPORT_CUSTOMERS,
    PERMISSIONS.EMAIL_SEND,
  ],
  WAREHOUSE: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.AUTH_REFRESH_TOKEN,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_EXPORT,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_EXPORT,
    PERMISSIONS.PRODUCT_UPLOAD_IMAGE,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_STOCK_IN,
    PERMISSIONS.INVENTORY_STOCK_OUT,
    PERMISSIONS.INVENTORY_MOVEMENT_VIEW,
    PERMISSIONS.INVENTORY_ALERTS_VIEW,
    PERMISSIONS.INVENTORY_ANALYTICS,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_UPDATE,
    PERMISSIONS.SALES_CONFIRM,
    PERMISSIONS.SALES_CANCEL,
    PERMISSIONS.RETURN_VIEW,
    PERMISSIONS.RETURN_CREATE,
    PERMISSIONS.RETURN_APPROVE,
    PERMISSIONS.RETURN_REJECT,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORT_INVENTORY,
  ],
  ACCOUNTS: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.AUTH_REFRESH_TOKEN,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_EXPORT,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_EXPORT,
    PERMISSIONS.CATEGORY_VIEW,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ALERTS_VIEW,
    PERMISSIONS.INVENTORY_ANALYTICS,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_DOWNLOAD,
    PERMISSIONS.INVOICE_EMAIL,
    PERMISSIONS.INVOICE_PAYMENT_UPDATE,
    PERMISSIONS.RETURN_VIEW,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORT_SALES,
    PERMISSIONS.REPORT_INVENTORY,
    PERMISSIONS.REPORT_CUSTOMERS,
    PERMISSIONS.EMAIL_SEND,
    PERMISSIONS.EMAIL_HISTORY,
  ],
};

/**
 * Check if a role has a specific permission.
 * @param {string} role - User role (ADMIN, SALES, WAREHOUSE, ACCOUNTS)
 * @param {string} permission - Permission string (e.g. 'CUSTOMER.CREATE')
 * @returns {boolean}
 */
export const hasPermission = (role, permission) => {
  if (!role || !permission) return false;
  // ADMIN has all permissions
  if (role === 'ADMIN') return true;
  const rolePerms = ROLE_PERMISSIONS[role];
  if (!rolePerms) return false;
  return rolePerms.includes(permission);
};

